#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flixtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flixtube
  template:
    metadata:
      labels:
        app: flixtube
    spec:
      containers: 
      - name: flixtube
        image: YOUR_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/flixtube:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: flixtube
spec:
  selector:
    app: flixtube
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000